добавляет вёрстку главной страницы и страницы каталога
summertime-fms/gleb-glacy pull request #2
Opened 2023-04-26 07:06 UTC by bga87

2023-04-26 08:45 UTC, summertime-fms requested changes
Разметка выглядит хорошо

Можно улучшить:
- Давать меньше классов либо сокращать сами классы, сейчас они очень длинные везде, это затрудняет восприятие разметки и написание стилей

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +            </ul>
сокращай классы, для лаконичности и удобства написания стилец в будущем. Можно просто header вместо page-header, nav/navigation вместо navigation-menu и так далее

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +          <button class="header-action-button button-search" type="button"><span class="visually-hidden">Поиск</span></button>
Каждый тег с новой строки. Можешь воспользоваться форматтером - prettier например. Устанавливается в вс код как расширение, затем выделяешь всю разметку/стили и нажимаешь Ctrl + Shift + P (если мак то Cmd) и в верхнем меню выбираешь Prettier и жмешь enter. Он за тебя все форматнет

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +        <p class="breadcrumbs">
это список обычно

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +        <p class="breadcrumbs">
а ссылки обернуть в li

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +          <p class="catalog-filter-sort">
параграф в качестве обертки не очень логичным кажется. Воспользуйся дивом. И точно ли тут нужна обертка?

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +              </li>
тоже можно сократить классы до filter

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +        <ol class="product-list">
порядок не имеет значения. Это ненумерованный список

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +              <img class="product-card-image" src="#" alt="">
для оптимизаций можно добавлять атрибут loading="lazy" контентным изображениям. Это сильно ускорит загрузку страницы. Подробнее можешь почитать в интернетах

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +          <a class="social-button-link" href="https://t.me/htmlacademy">
ссылки не внешние сайты лучше помечать атрибутом target="_blank" чтобы страница открывалась в новом окне и пользователь не покиадл текущий сайт.

2023-04-26 08:45 UTC, summertime-fms commented on catalog-creamy.html
> +      <p class="copyright-text">Сделано в <a class="developer-text-link" href="https://htmlacademy.ru">.html academy</a> © 2021</p>
с новой строки тег

2023-04-26 08:45 UTC, summertime-fms commented on index.html
> +            <img class="product-slider-image" src="#" alt="Пломбир с клубничным джемом в вафельном рожке">
Если есть однотипный контент (например 3 слайда где ВСЕГДА будет заголовок картинка и текст и более ничего) то можно от обертки будет писать стили по типу .product-slider-item h3 {}

2023-04-26 08:45 UTC, summertime-fms commented on index.html
> +            <img class="product-slider-image" src="#" alt="Пломбир с клубничным джемом в вафельном рожке">
я к тому что не всегда нужно каждому элементу доабвлять класс, в некоторых случаях можно сократить разметку

2023-04-26 08:45 UTC, summertime-fms commented on index.html
> +            <p class="feature-description">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</p>
Можно без параграфа, просто текст внутри li

2023-04-26 08:45 UTC, summertime-fms commented on index.html
> +            <input id="delivery-phone" type="text" name="delivery-phone" placeholder="+7 800 999-00-00">
type tel

2023-04-26 13:27 UTC, bga87 commented on catalog-creamy.html
> +          <a class="social-button-link" href="https://t.me/htmlacademy">
добавил всем внешним ссылкам атрибут target со значением "_blank"

2023-04-26 13:30 UTC, bga87 commented on catalog-creamy.html
> +          <button class="header-action-button button-search" type="button"><span class="visually-hidden">Поиск</span></button>
перенес, Prettier у меня в vscode установлен)

2023-04-26 14:33 UTC, bga87 commented on catalog-creamy.html
> +              <img class="product-card-image" src="#" alt="">
Почитал, осознал, добавил)

2023-04-26 14:40 UTC, bga87 commented on catalog-creamy.html
> +      <p class="copyright-text">Сделано в <a class="developer-text-link" href="https://htmlacademy.ru">.html academy</a> © 2021</p>
Не суди строго, но здесь я оставлю как было, потому что вид верстки с разрывом в середине предложения для переноса ссылки наносит "неприемлемый ущерб" моему "чувству прекрасного"))) тем более стайлгайд академии не против

2023-04-26 15:14 UTC, bga87 commented on index.html
> +            <img class="product-slider-image" src="#" alt="Пломбир с клубничным джемом в вафельном рожке">
классы удалил

2023-04-27 00:19 UTC, bga87 commented on index.html
> +            <p class="feature-description">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</p>
убрал

2023-04-27 01:27 UTC, bga87 commented on catalog-creamy.html
> +              </li>
сократил

2023-04-27 01:31 UTC, bga87 commented on catalog-creamy.html
> +        <ol class="product-list">
но ведь у нас каталог с фильтром, в котором выбран один из вариантов сортировки результатов, т.е. карточки товаров выведены в определенном порядке. Разве здесь не ol?

2023-04-27 03:03 UTC, bga87 commented on catalog-creamy.html
> +        <ol class="product-list">
Спека говорит: "The ol element represents a list of items, where the items have been **intentionally ordered**, such that **changing the order would change the meaning of the document.**" 
У нас карточки товара намеренно упорядочены, т.к. у нас фильтр. Вот если бы фильтра не было, то да - тут нужен был бы ul. Такая моя логика)

2023-04-27 03:05 UTC, bga87 commented on catalog-creamy.html
> +        <ol class="product-list">
Ссылка на цитату из спеки: https://html.spec.whatwg.org/multipage/grouping-content.html#the-ol-element:~:text=The%20ol%20element%20represents%20a%20list%20of%20items%2C%20where%20the%20items%20have%20been%20intentionally%20ordered%2C%20such%20that%20changing%20the%20order%20would%20change%20the%20meaning%20of%20the%20document.

2023-04-27 03:21 UTC, bga87 commented on catalog-creamy.html
> +        <p class="breadcrumbs">
да, реализацию в виде списка я видел в материалах академии к разделу (кстати опять таки вопрос, почему там это реализовано через ul? Ведь крошки по сути не что иное как "путь", который ведет к текущей странице, и должны идти в определенном порядке. Мы же не можем, например, в пути к файлу переставить названия каталогов, которые к нему ведут, как нам заблагорассудится - путь просто станет невалиден, т.е. порядок важен)
а моя реализация крошек - не что иное как рекомендация спеки по верстке данного элемента: https://html.spec.whatwg.org/multipage/semantics-other.html#rel-up

2023-04-27 04:35 UTC, bga87 commented on catalog-creamy.html
> +          <p class="catalog-filter-sort">
Почему не логично? Опять таки сошлюсь на спецификацию...
1. The p element represents a **paragraph**. https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element
2. A paragraph is typically a run of **phrasing content** that forms a block of text with one or more sentences that discuss a particular topic, as in typography, but **can also be used for more general thematic grouping**. For instance, an address is also a paragraph, as is a **part of a form**, a byline, or a stanza in a poem. https://html.spec.whatwg.org/multipage/dom.html#paragraphs

И label и select по спецификации относятся к phrasing content, поэтому могут быть внутри p - тут противоречий нет. Кроме того там прямо в приведенном мной тексте говорится, что часть формы можно рассматривать как параграф. В данном случае авторы спецификации подчеркивают, что параграф используется не как элемент для группировки чисто текстового содержимого, а как элемент общей тематической группировки элементов (more general thematic grouping). Кроме того, там есть примеры кода, где label'ы с разными input'ами обернуты в p.

Вопрос №2; нужна ли здесь обертка? Я оборачиванием в p хотел дополнительно подчеркнуть и отделить эту часть формы от остальных, которые сгруппированы в fieldset'ы. С точки зрения семантической разметки, которая практикуется в этом разделе, смысл оборачивания в div для меня неочевиден. При этом я осознаю, что для стилизации в дальнейшем возможно в div придется завернуть. На текущем этапе, если ты считаешь, что обертка не нужна, то я ее просто удалю.

2023-04-27 08:23 UTC, summertime-fms commented on catalog-creamy.html
> +        <p class="breadcrumbs">
Касательно отличий ol от ul в хлебных крошках - если задуматься то список в бытовом нашем понимании (список продуктов например) на самом деле не список, а множество. Имеет ли значение в каком порядке ты записал продукты для покупки? нет. Это просто перечисление не нагруженное связностью и строгим порядком элементов. То же самое с тегом ol - это просто перечисление, которое добавляет цифры к началу пункта. И изначально этот тег задумывался больше для визуального аспекта нежели семантического (так как речи о семантики в те времена не шло). 
Подводя итог - я вообще думаю что разницы для семантики в конкретном случае нет.  Я тут могу ошибаться но на самом деле это не играет никакого значения, потому что от того что ты используешь не ul а ol и наоборот - ничего не поменяется.  Семантика так и так будет, компонент так и так будет сверстан. 

Касательно спеки - можешь оставить и такой вариант, я указал лишь на то что сейчас уже обычно делают списком хлебные крошки, о чем и говорит академия. Но это не значит что делать по другому воспрещается.

2023-04-27 08:42 UTC, summertime-fms commented on catalog-creamy.html
> +          <p class="catalog-filter-sort">
ты можешь оставить это как есть, т.к. как и в случае с крошками - ничего не изменится от того будет там параграф или див. 
почему я написал о нелогичности: див - безликая обертка а параграф - обертка под текст. В данном случае там внутри не текст а еще какие то теги и контролы формы. Спека говорит в первую очередь о том что параграф предназначен для текста но ТАКЖЕ может использоваться и для группировки элементов. 
Вывод: тут нет ошибки как таковой, есть лишь смысловой окрас. Что тебе наиболее близко то ты и выбираешь.

2023-04-27 08:46 UTC, summertime-fms commented on catalog-creamy.html
> +        <p class="breadcrumbs">
Касательно спеки - можешь оставить и такой вариант, я указал лишь на то что сейчас уже обычно делают списком хлебные крошки, о чем и говорит академия. Но это не значит что делать по другому воспрещается.

Касательно отличий ul от ol - я думаю что ol логичнее.

2023-04-27 08:48 UTC, summertime-fms requested changes

2023-04-27 08:48 UTC, summertime-fms commented on catalog-creamy.html
> +        <ol class="product-list">
Да, можно сделать нумерованным, в прицнипе логично

2023-04-28 00:25 UTC, bga87 commented on catalog-creamy.html
> +            </ul>
провел ревизию классов - сократил названия, удалил некоторые

2023-04-28 00:26 UTC, bga87 commented on catalog-creamy.html
> +        <p class="breadcrumbs">
Пока оставлю как есть

2023-04-28 00:48 UTC, bga87 commented
внес правки в вёрстку по твоим замечаниям

2023-04-28 10:16 UTC, merged